[MERL-513] FaustWP
wpengine/faustjs pull request #1049
Opened 2022-09-30 09:39 UTC by theodesp

## Description

## Related Issue(s):

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2022-09-30 16:06 UTC, TeresaGobble commented
Hi Theo- there are some instances of axl in the axl-website folder; is this area of the repo meant to be renamed as well in this ticket? If not, I can take care of that when I complete MERL-522 (Stage new Faust documentation site on Atlas).

2022-09-30 16:09 UTC, TeresaGobble commented
> Hi Theo- thank you for your hard work, this is looking great! There are some instances of `axl` in the `axl-website` folder; is this area of the repo meant to be renamed as well in this ticket? If not, I can take care of that when I complete MERL-522 (Stage new Faust documentation site on Atlas).

Ah, I see from the ticket that its scope is for the packages only, so please disregard the above.

2022-09-30 19:40 UTC, TeresaGobble requested changes
Thank you for tackling this for us, Theo! I made some suggestions to revert the faust.org -> faustjs.org, since we aren't able to get the faust.org domain- everything else LGTM! 😊

2022-09-30 19:40 UTC, TeresaGobble commented on packages/faustwp-core/src/server/auth/middleware.ts
> + * @see https://faust.org/docs/next/guides/auth
```suggestion
 * @see https://faustjs.org/docs/next/guides/auth
```

2022-09-30 19:40 UTC, TeresaGobble commented on packages/faustwp-core/src/server/auth/middleware.ts
> + * @see https://faust.org/docs/next/guides/auth
```suggestion
 * @see https://faustjs.org/docs/next/guides/auth
```

2022-09-30 19:40 UTC, TeresaGobble commented on packages/faustwp-core/DEVELOPMENT.md
> +- `main` - This branch is used to deploy changes to [faust.org](https://faust.org)
```suggestion
- `main` - This branch is used to deploy changes to [faustjs.org](https://faustjs.org)
```

2022-09-30 19:40 UTC, TeresaGobble commented on packages/faustwp-core/DEVELOPMENT.md
> +The docs on faust.org are automatically built on pushes to `main`. Updating the docs on `main` will update faust.org within 10 minutes.
```suggestion
The docs on faustjs.org are automatically built on pushes to `main`. Updating the docs on `main` will update faustjs.org within 10 minutes.
```

2022-09-30 19:40 UTC, TeresaGobble commented on packages/faustwp-core/DEVELOPMENT.md
> +After a successful release, a PR from `canary` to `main` is automatically created. Review and merge this PR to update faust.org.
```suggestion
After a successful release, a PR from `canary` to `main` is automatically created. Review and merge this PR to update faustjs.org.
```

2022-10-03 11:41 UTC, theodesp commented
@TeresaGobble changes implemented you can approve now thank you!

2022-10-03 13:23 UTC, TeresaGobble approved these changes
LGTM, thank you Theo!

2022-10-03 14:34 UTC, merged