Added Atlas deployment guide and sidebar link
wpengine/faustjs pull request #1174
Opened 2022-12-05 19:43 UTC by TeresaGobble

## Description

This PR introduces the Atlas deployment guide we had in our [Legacy documents](https://legacy.faustjs.org/docs/going-to-production/deployment) for Faustjs.org.

Please double check the Node versioning in the first paragraph: `Faust.js supports Node.js v14.x and v16.x. Please make sure you are using a Node.js version that is compatible when deploying to avoid unexpected errors.`

2022-12-05 21:58 UTC, josephfusco commented on internal/faustjs.org/docs/going-to-production/deployment.mdx
> +- Automatic installation of required plugins ([FaustWP](https://wordpress.org/plugins/faustwp/), [WPGraphQL](https://wordpress.org/plugins/wp-graphql/), etc.)
```suggestion
- Automatic installation of required WordPress plugins ([Faust](https://wordpress.org/plugins/faustwp/), [WPGraphQL](https://wordpress.org/plugins/wp-graphql/), etc.)
```

2022-12-05 21:59 UTC, josephfusco commented on internal/faustjs.org/docs/going-to-production/deployment.mdx
> +- Automatic configuration of FaustWP headless settings
```suggestion
- Automatic configuration of the Faust WordPress plugin's settings
```

2022-12-05 22:00 UTC, josephfusco commented on internal/faustjs.org/sidebars.js
> +      label: 'Migration from Old Faust',
```suggestion
      label: 'Migration from legacy Faust',
```

2022-12-05 22:02 UTC, josephfusco requested changes
Great work! Left some minor suggestions

2022-12-05 22:22 UTC, TeresaGobble commented
> Great work! Left some minor suggestions

Awesome catches, Joe, thank you so much!

2022-12-06 02:33 UTC, josephfusco approved these changes
🔥

2022-12-06 02:40 UTC, merged