MERL-617: plugin guide
wpengine/faustjs pull request #1397
Opened 2023-04-24 15:42 UTC by matthewguywright

## Description
Added a faust plugin guide that has links to relevant areas and an example.

2023-04-24 16:22 UTC, theodesp commented on internal/faustjs.org/docs/guides/plugins.mdx
> +import { MyPlugin } from './MyPlugin.tsx';
You cannot import a `tsx` file in javascript so this would fail.

2023-04-24 16:23 UTC, theodesp commented on internal/faustjs.org/docs/guides/plugins.mdx
> +```js
```suggestion
```ts
```

2023-04-24 16:24 UTC, theodesp commented on internal/faustjs.org/docs/guides/plugins.mdx
> +```js
```suggestion
```ts
```

2023-04-24 16:29 UTC, TeresaGobble requested changes
Hi Matt, nice work! 👍  In addition to Theo's comments, we need this to be added to `sidebars.js`, here: https://github.com/wpengine/faustjs/blob/canary/internal/faustjs.org/sidebars.js 

I'll check the formatting when it's up on the page ✅

2023-04-25 01:50 UTC, TeresaGobble reviewed
Nicely done Matt! Just left a few suggestions for clarity, and to begin following the new template for a how-to guide! 🥳

2023-04-25 01:50 UTC, TeresaGobble commented on internal/faustjs.org/docs/guides/plugins.mdx
> +The experimental config object is used to setup plugins via the `experimentalPlugins` property. It's a property that takes an array of plugin class instances. You or the end user can then implement t
```suggestion
The experimental config object is used to set up plugins via the `experimentalPlugins` property. It's a property that takes an array of plugin class instances. You or the end user can then implement the plugin by adding it to the `experimentalPlugins` property in the App's `faust.config.js` file. See the example below:
```

2023-04-25 01:50 UTC, TeresaGobble commented on internal/faustjs.org/docs/guides/plugins.mdx
> +[InMemoryCache](https://www.apollographql.com/docs/react/api/cache/InMemoryCache/)
I would suggest adding clarity on this link:

```suggestion
`InMemoryCache` is the cache used by almost every instance of ApolloClient. Read more about `InMemoryCache` [here.](https://www.apollographql.com/docs/react/api/cache/InMemoryCache/)
```

2023-04-25 01:50 UTC, TeresaGobble commented on internal/faustjs.org/docs/guides/plugins.mdx
> +It uses the `addFilter` inside a Faust plugin called `PersistedQueriesPlugin`. It filters `apolloClientOptions` and pulls the link as `existingLink`. If the `existingLink` is an instance of `HttpLink
```suggestion
It uses the `addFilter` inside a Faust plugin called `PersistedQueriesPlugin`. It filters `apolloClientOptions` and pulls the link as `existingLink`. If the `existingLink` is an instance of `HttpLink`, it adds the `existingLink` to the `persistedQueriesLink`. If it's not an instance of `HttpLink`, it adds the `httpLink` to the `persistedQueriesLink`.
```

2023-04-25 01:50 UTC, TeresaGobble commented on internal/faustjs.org/docs/guides/plugins.mdx
> +For further learning about the filters check out the [Faust Filters](https://faustjs.org/docs/plugin-system/filters).
```suggestion
For further learning about Faust filters, check out the Faust Filters, [here.](https://faustjs.org/docs/plugin-system/filters).
```

2023-04-25 14:59 UTC, TeresaGobble reviewed
Some last fixes added.

2023-04-25 14:59 UTC, TeresaGobble commented on internal/faustjs.org/docs/guides/plugins.mdx
> +Prerequisites
```suggestion
Prerequisites:
```

2023-04-25 14:59 UTC, TeresaGobble commented on internal/faustjs.org/docs/guides/plugins.mdx
> +For further learning about Faust filters, check out the Faust Filters, [here.](https://faustjs.org/docs/plugin-system/filters).
```suggestion
For further learning about Faust filters, check out the Faust Filters, [here](https://faustjs.org/docs/plugin-system/filters).
```

2023-04-25 15:14 UTC, merged