Fix drafts for unpublished posts
wpengine/faustjs pull request #1438
Opened 2023-05-31 20:11 UTC by josephfusco

## Tasks

- [X] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.

## Description

These changes fix a bug where Faust's seed query was failing when attempting to view an unpublished WordPress post w/ a draft status.

## Testing

1. Checkout this branch: `MERL-931-preview-for-draft`
2. Run `npm run build`
3. Go to `examples/faustwp-getting-started/.env.local` and update NEXT_PUBLIC_WORDPRESS_URL to a test WordPress site.
4. Run `npm run dev -w @faustwp/getting-started-example`
5. Go to your WordPress site, create a new post with a title & content and select "save as draft", then preview in a new tab.
6. Observe that the draft post is displaying the title & content.

You can also test the new Seed query by directly testing it out in GraphiQL.

### Query

```graphql
query GetSeedNode($id: ID = 0, $uri: String = "", $asPreview: Boolean = false) {
  ... on RootQuery @skip(if: $asPreview) {
    nodeByUri(uri: $uri) {
      __typename
      ...GetNode
    }
  }
  ... on RootQuery @include(if: $asPreview) {
    contentNode(id: $id, idType: DATABASE_ID, asPreview: true) {
      __typename
      ...GetNode
    }
  }
}

fragment GetNode on UniformResourceIdentifiable {
  __typename
  uri
  id
  ...DatabaseIdentifier
  ...ContentType
  ...User
  ...TermNode
  ...ContentNode
  ...MediaItem
  ...Page
}

fragment DatabaseIdentifier on DatabaseIdentifier {
  databaseId
}

fragment MediaItem on MediaItem {
  id
  mimeType
}

fragment ContentType on ContentType {
  name
  isFrontPage
  isPostsPage
}

fragment Page on Page {
  isFrontPage
  isPostsPage
}

fragment TermNode on TermNode {
  isTermNode
  slug
  taxonomyName
}

fragment ContentNode on ContentNode {
  isContentNode
  slug
  contentType {
    node {
      name
    }
  }
  template {
    templateName
  }
}

fragment User on User {
  name
  userId
  databaseId
}
```

### Variables

Example GraphQL variables for testing a draft post:

```json
{
  "asPreview": true,
  "id": 150
}
```

Example GraphQL variables for testing a published post:

```json
{
  "uri": "index.php?p=150"
}
```

## Screenshots

<img width="1879" alt="Screenshot 2023-06-05 at 3 37 39 PM" src="https://github.com/wpengine/faustjs/assets/6676674/89c9d984-8fd3-48a3-94bc-c7044534e03d">

<img width="1890" alt="Screenshot 2023-06-05 at 3 37 21 PM" src="https://github.com/wpengine/faustjs/assets/6676674/6e547703-f7c5-4550-86a1-a4574aacb3e6">

2023-06-01 14:35 UTC, matthewguywright submitted a review, later dismissed

2023-06-05 19:55 UTC, blakewilson reviewed
Nice @josephfusco! Thanks for the PR. Left some comments.

2023-06-05 19:55 UTC, blakewilson commented on examples/next/faustwp-getting-started/possibleTypes.json
I think these possible types crept in by accident.

2023-06-05 19:55 UTC, blakewilson commented on packages/faustwp-core/src/components/WordPressTemplate.tsx
> +      let databaseId = '';
We're not reassigning this variable. Could we define it instead on line 110 and drop this line?

2023-06-05 19:55 UTC, blakewilson commented on packages/faustwp-core/src/components/WordPressTemplate.tsx
>            uri: seedQueryUri,
We should only include the `uri` variable if `isPreview` = `false`

2023-06-05 19:55 UTC, blakewilson commented on packages/faustwp-core/src/components/WordPressTemplate.tsx
> +          id: databaseId,
We should only include the `id` variable if `isPreview` = `true`

2023-06-05 19:55 UTC, blakewilson commented on .changeset/sweet-items-remember.md
Since this changes the seed query in a pretty big way (used to only receive `data.node`, now it receives `data.contentNode` and `data.nodeByUri`), we may be better of making this a `minor` (breaking change) for those that may be manipulating the seed query via the filter. Anyone who is doing that will need to refactor to use the new `nodeByUri`/`contentNode` syntax opposed to `node`.

2023-06-05 20:44 UTC, blakewilson commented on packages/faustwp-core/src/components/WordPressTemplate.tsx
> +      let databaseId = '';
However `queryArgs` is within the control statement in which `databaseId` is being assigned, so defining it there would still allow you to use it within `queryArgs`

2023-06-05 20:44 UTC, blakewilson commented on .changeset/sweet-items-remember.md
> +Previously the seed query would only receive `data.node`. These changes update the seed query to now recieve both `data.contentNode` & `data.nodeByUri`. Note that projects hooking into Faust's `seedQ
nice 👍

2023-06-05 20:46 UTC, blakewilson commented on packages/faustwp-core/src/components/WordPressTemplate.tsx
> +          ...(isPreview && { asPreview: true }),
Interesting use of conditional spreading properties. I'll have to use this in the future.

2023-06-05 21:23 UTC, blakewilson commented
Strange, I'm encountering this error when trying to preview a draft post:

<img width="1008" alt="Screenshot 2023-06-05 at 4 17 05 PM" src="https://github.com/wpengine/faustjs/assets/5946219/12751cbb-6992-4c6a-9379-5cf0bd442324">

This is the URL of my preview page:

```
http://localhost:3000/preview?p=520&preview=true&previewPathname=%2F%3Fp%3D520&typeName=Post
```

As you can see, the draft post has a databaseId assigned 520 from the preview URL. This databaseId is used when getting the seed node for this preview post using `contentNode`. However, the returned seed node has a database ID of `521`:

```
{
  __typename: "Post",
  contentType: {
    __typename: "ContentNodeToContentTypeConnectionEdge",
    node: { __typename: "ContentType", name: "post" },
  },
  databaseId: 521,
  id: "cG9zdDo1MjE=",
  isContentNode: true,
  slug: "520-revision-v1",
  template: { __typename: "DefaultTemplate", templateName: "Default" },
  uri: "http://localhost:3000/?p=520&preview=true&previewPathname=%2F%3Fp%3D520&typeName=Post",
};
```

This then leads to the actual preview data request to use the wrong databaseId `521`, and returns `null` for `post` 🤔

2023-06-06 14:29 UTC, blakewilson commented
> Strange, I'm encountering this error when trying to preview a draft post:
> 
> <img alt="Screenshot 2023-06-05 at 4 17 05 PM" width="1008" src="https://user-images.githubusercontent.com/5946219/243478551-12751cbb-6992-4c6a-9379-5cf0bd442324.png">
> This is the URL of my preview page:
> 
> ```
> http://localhost:3000/preview?p=520&preview=true&previewPathname=%2F%3Fp%3D520&typeName=Post
> ```
> 
> As you can see, the draft post has a databaseId assigned 520 from the preview URL. This databaseId is used when getting the seed node for this preview post using `contentNode`. However, the returned seed node has a database ID of `521`:
> 
> ```
> {
>   __typename: "Post",
>   contentType: {
>     __typename: "ContentNodeToContentTypeConnectionEdge",
>     node: { __typename: "ContentType", name: "post" },
>   },
>   databaseId: 521,
>   id: "cG9zdDo1MjE=",
>   isContentNode: true,
>   slug: "520-revision-v1",
>   template: { __typename: "DefaultTemplate", templateName: "Default" },
>   uri: "http://localhost:3000/?p=520&preview=true&previewPathname=%2F%3Fp%3D520&typeName=Post",
> };
> ```
> 
> This then leads to the actual preview data request to use the wrong databaseId `521`, and returns `null` for `post` 🤔

@jasonbahl Have you seen this before?

2023-06-06 16:10 UTC, mindctrl requested changes

2023-06-06 16:11 UTC, mindctrl commented on .changeset/sweet-items-remember.md
> +**BREAKING** - Fixed seed query failing when attempting to view an unpublished WordPress with a draft status.
```suggestion
**BREAKING** - Fixed seed query failing when attempting to view an unpublished WordPress post with a draft status.
```

2023-06-06 17:18 UTC, blakewilson commented
Tested this behavior and it seems to be an issue in WPGraphQL. I opened an issue:

https://github.com/wp-graphql/wp-graphql/issues/2832

2023-06-06 18:17 UTC, blakewilson commented
> Tested this behavior and it seems to be an issue in WPGraphQL. I opened an issue:
> 
> [wp-graphql/wp-graphql#2832](https://github.com/wp-graphql/wp-graphql/issues/2832)

Disregard!

2023-06-06 18:18 UTC, blakewilson approved these changes
LGTM! nice work

2023-06-06 19:53 UTC, mindctrl approved these changes

2023-06-06 19:53 UTC, merged