RFC: Set 404 Revalidate timer to 900 seconds.
wpengine/faustjs pull request #1639
Opened 2023-11-09 12:43 UTC by theodesp

## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

Sets the default ISR revalidate timer on 404 pages

## Related Issue(s):

## Testing

1. Checkout and Build the project.
2. Run a curl command that will tigger a 404 response.
3. You should see the following header in cache-control:
` Cache-Control: s-maxage=900, stale-while-revalidate`

## Screenshots

**Before**
```
❯ curl -vvv http://localhost:3000/222 | grep cache-control
...
>
< HTTP/1.1 404 Not Found
< x-using: faust
< x-nextjs-cache: HIT
< Cache-Control: s-maxage=31536000, stale-while-revalidate
< ETag: "inm7ps8d27200"
< Content-Type: text/html; charset=utf-8
< Content-Length: 2592
< Vary: Accept-Encoding
< Date: Thu, 09 Nov 2023 12:28:23 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

**After**

```
❯ curl -vvv http://localhost:3000/222 | grep cache-control
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /222 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 404 Not Found
< x-using: faust
< x-nextjs-cache: HIT
< Cache-Control: s-maxage=900, stale-while-revalidate
< ETag: "7hstphb9w0200"
< Content-Type: text/html; charset=utf-8
< Content-Length: 2592
< Vary: Accept-Encoding
< Date: Thu, 09 Nov 2023 12:33:07 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [2592 bytes data]
```

## Documentation Changes

## Dependant PRs

2023-11-13 15:09 UTC, blakewilson commented on packages/faustwp-core/src/server/sitemaps/getSitemapProps.tsx
[`getSitemapProps`](https://faustjs.org/reference/getsitemapprops) can only be ran within a [`getServerSideProps`](https://nextjs.org/docs/pages/api-reference/functions/get-server-side-props) function, which doesn't support `revalidate`, so we should not have to modify this file.

2023-11-13 15:11 UTC, blakewilson commented
@theodesp You may want to update your testing instructions to mention that the user needs to also:

1. Build the example project
2. Run the project in production mode (`npm run start`) vs in dev mode (`npm run dev`)

2023-11-13 15:19 UTC, blakewilson requested changes

2023-11-13 15:19 UTC, blakewilson commented on packages/faustwp-core/src/getWordPressProps.tsx
Outside of `getStaticProps`, `revalidate` can not be used alongside `notFound`. If the `revalidate` property is found in `getServerSideProps` a 500 error is thrown:
![Screenshot 2023-11-13 at 9 14 03 AM](https://github.com/wpengine/faustjs/assets/5946219/77ba7154-1aab-4ef2-9a49-666a64b36f8a)

![Screenshot 2023-11-13 at 9 14 24 AM](https://github.com/wpengine/faustjs/assets/5946219/94273d3f-8e27-4a84-b470-b065536c887d)

We'll want to conditionally add this property only when `!isSSR()`.

You can test this manually by updating your `[...wordPressNode].js` file to use `getServerSideProps` instead of `getStaticProps`:

```js
import { getWordPressProps, WordPressTemplate } from '@faustwp/core';

export default function Page(props) {
  return <WordPressTemplate {...props} />;
}

export function getServerSideProps(ctx) {
  return getWordPressProps({ ctx });
}
```

2023-11-15 15:23 UTC, blakewilson requested changes
Let's add back the carrots to the example project's `package.json` but other than that, this looks good to go! Nice work @theodesp

2023-11-15 15:23 UTC, blakewilson commented on examples/next/faustwp-getting-started/package.json
> +    "@faustwp/core": "1.2.0",
Were the carrots removed intentionally?

2023-11-16 11:19 UTC, theodesp commented on examples/next/faustwp-getting-started/package.json
> +    "@faustwp/core": "1.2.0",
I will revert

2023-11-16 15:26 UTC, blakewilson approved these changes

2023-11-17 10:53 UTC, merged