[Merl 1256] Bug fix. Generate Autosave is missing from Post/Page Previews
wpengine/faustjs pull request #1644
Opened 2023-11-13 13:51 UTC by theodesp

## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

Fixes missing call to `autosave` when clicking on the Preview links.

## Related Issue(s):

## Testing

1. Checkout this branch that includes changes to the faustwp plugin
2. Using the updated faustwp plugin, create a new post & save as draft (do not publish)
3. Observe that both preview links correctly resolve to display draft content.
4. Verify that the draft content is also presented in the headless site.

## Screenshots

## Documentation Changes

## Dependant PRs

2023-11-13 13:55 UTC, theodesp commented on plugins/faustwp/includes/replacement/previewlinks.js
> -      const clonedHeaderLink = headerLink.cloneNode(true);
No DOM modifications allowed under React managed DOM

<img width="872" alt="Screenshot 2023-11-13 at 13 32 12" src="https://github.com/wpengine/faustjs/assets/328805/b44965c0-4b46-46df-9bbd-232439db53a1">

2023-11-13 14:37 UTC, blakewilson commented
@theodesp I've tested this and both existing previews and draft previews no longer work for me.

When requesting an existing post preview, the `post` comes back as `null`:
![Screenshot 2023-11-13 at 8 32 02 AM](https://github.com/wpengine/faustjs/assets/5946219/1228b3f2-0770-45d1-bf97-fe0462402240)

When requesting a new draft post, the `previewPathname` is no longer being added to the URL, which is causing an error on the Faust/Next side to be thrown. Oddly, when hovering over the preview button you can see in the bottom left corner, the URL does include the `previewPathname`:
![Screenshot 2023-11-13 at 8 27 35 AM](https://github.com/wpengine/faustjs/assets/5946219/5f826bef-dd2b-421e-9e9a-ae0604b22965)

But once the link is clicked, it is removed from the URL:
![Screenshot 2023-11-13 at 8 27 51 AM](https://github.com/wpengine/faustjs/assets/5946219/da819c15-af19-46bf-a98f-7b060c841ce2)

2023-11-14 10:30 UTC, theodesp commented on package.json
> +    "axios": "^1.6.1"
https://github.com/wpengine/faustjs/pull/1650

2023-11-14 11:08 UTC, theodesp commented
@blakewilson  I've updated the code. It should work now:

https://github.com/wpengine/faustjs/assets/328805/c6fc76db-a589-4a6e-a87e-52aa69b7b500

2023-11-15 10:56 UTC, theodesp commented
Lint error looks like relevant to this

https://github.com/woocommerce/woocommerce-sniffs/issues/34

Need to investigate

2023-11-15 15:46 UTC, blakewilson commented
> @theodesp I've tested this and both existing previews and draft previews no longer work for me.
> 
> When requesting an existing post preview, the `post` comes back as `null`: ![Screenshot 2023-11-13 at 8 32 02 AM](https://user-images.githubusercontent.com/5946219/282490401-1228b3f2-0770-45d1-bf97-fe0462402240.png)
> 
> When requesting a new draft post, the `previewPathname` is no longer being added to the URL, which is causing an error on the Faust/Next side to be thrown. Oddly, when hovering over the preview button you can see in the bottom left corner, the URL does include the `previewPathname`: ![Screenshot 2023-11-13 at 8 27 35 AM](https://user-images.githubusercontent.com/5946219/282490919-5f826bef-dd2b-421e-9e9a-ae0604b22965.png)
> 
> But once the link is clicked, it is removed from the URL: ![Screenshot 2023-11-13 at 8 27 51 AM](https://user-images.githubusercontent.com/5946219/282491116-da819c15-af19-46bf-a98f-7b060c841ce2.png)

I've realized this was due to a bug in Faust/Safari, so this may be unrelated.

2023-11-15 15:47 UTC, blakewilson approved these changes
Nice work @theodesp! I've tested locally for published posts and draft posts and both work as expected.

2023-11-15 16:00 UTC, mindctrl commented on plugins/faustwp/includes/replacement/callbacks.php
> +add_filter( 'rest_prepare_page', __NAMESPACE__ . '\\preview_link_in_rest_response', 10, 2 );
Can we add some `has_action` tests for these? They seem like silly tests, but I've had them catch unintentional removals before, so I typically add them.

2023-11-15 16:31 UTC, mindctrl requested changes
Left comment about tests. Also there's a merge conflict now.

2023-11-17 19:55 UTC, matthewguywright approved these changes

2023-11-21 18:38 UTC, TeresaGobble commented
Good afternoon Theo! I tried running this branch using the app-router example to play with it (it's connected to my test site via the `.env.local`, and I have the active plugin symlinked into my test site). I have received an error I haven't seen before when running `npm run dev`, below: 
<img width="935" alt="image" src="https://github.com/wpengine/faustjs.org/assets/50935135/199b6cb7-06e7-448e-8ff2-f7353f604f14">

I've already deleted `node_modules

Is there something amiss with the way I'm approaching this for testing?

2023-11-21 18:55 UTC, TeresaGobble commented
Apologies for accidentally closing this, typing in github and my focus jumped to `close with comment`.

2023-11-27 17:01 UTC, merged