MERL-1712: custom toolbar example
wpengine/faustjs pull request #1725
Opened 2024-01-12 16:10 UTC by matthewguywright

## Description
Added an example for customizing the toolbar.

## Testing

1. Setup a faust project using the custom-toolbar example
2. Login using the button on the main frontpage template to authenticate
3. Toolbar should display with the custom elements showing from CustomToolbar.tsx in the /plugins folder.

## Screenshots
Logged Out:
![Screenshot 2024-01-12 at 10 09 19 AM](https://github.com/wpengine/faustjs/assets/1815200/23b53a73-70ad-49e6-8840-e2243a161890)

Logged In:
![Screenshot 2024-01-12 at 10 09 28 AM](https://github.com/wpengine/faustjs/assets/1815200/4bd8ae08-a2fd-46e3-a073-25afd674250e)

2024-01-12 17:06 UTC, mindctrl requested changes
Love the example being documentation. Nice work. Made some grammar suggestions.

2024-01-12 17:06 UTC, mindctrl commented on examples/next/custom-toolbar/README.md
> +See the [Getting Started](https://faustjs.org/tutorial/get-started-with-faust) to setup your base Faust project. In the tutorial you will see in the Quick Start section's first step that it says `To
```suggestion
See the [Getting Started](https://faustjs.org/tutorial/get-started-with-faust) to set up your base Faust project. In the tutorial you will see in the Quick Start section's first step that it says `To create a Faust project, run`:
```

2024-01-12 17:06 UTC, mindctrl commented on examples/next/custom-toolbar/README.md
> +To view the toolbar, make sure you have completed the Getting Started steps and then click `Login`. After you are logged in and authenticated you will see the toolbar at the top of the template.
```suggestion
To view the toolbar, make sure you have completed the Getting Started steps and then click `Log In`. After you are logged in and authenticated you will see the toolbar at the top of the template.
```

2024-01-12 17:06 UTC, mindctrl commented on examples/next/custom-toolbar/wp-templates/front-page.js
> +              <code>Login</code> button.
```suggestion
              <code>Log In</code> button.
```

2024-01-12 17:06 UTC, mindctrl commented on examples/next/custom-toolbar/wp-templates/front-page.js
> +            <button onClick={loginHandler}>Login</button>
```suggestion
            <button onClick={loginHandler}>Log In</button>
```

2024-01-12 17:06 UTC, mindctrl commented on examples/next/custom-toolbar/wp-templates/front-page.js
> +              <code>Logout</code> button.
```suggestion
              To log out and go back to the unauthenticated page, click on the{' '}
              <code>Log Out</code> button.
```

2024-01-12 17:06 UTC, mindctrl commented on examples/next/custom-toolbar/wp-templates/front-page.js
> +            <button onClick={() => logout()}>Logout</button>
```suggestion
            <button onClick={() => logout()}>Log Out</button>
```

2024-01-16 15:19 UTC, theodesp commented
@matthewguywright Do we really need a full blown example project here?

- Developers might get confused about where to find the new toolbar code.
- We have another copy of the site which is code duplication.

I suggest you remove all the extra parts and keep it very simple and with not duplicated components.

2024-01-18 00:56 UTC, closed without merging

2024-01-18 00:56 UTC, matthewguywright commented
Moving to a more bare bones setup.