MERL-1712: custom toolbar v2
wpengine/faustjs pull request #1745
Opened 2024-01-19 15:25 UTC by matthewguywright

## Description
Custom Toolbar example

## Testing
1. Setup a faust project using the custom-toolbar example
2. Login using the button on the main frontpage template to authenticate
3. Toolbar should display with the custom elements showing from CustomToolbar.tsx in the /plugins folder.

## Screenshots

2024-01-22 18:16 UTC, matthewguywright commented on examples/next/custom-toolbar/.github/workflows/build.yml
> +name: Build
Updated.

2024-01-22 19:26 UTC, blakewilson requested changes
It looks like the entire `.github` folder at the root was removed. You can restore it by running:

```
git checkout canary .github
```

2024-01-22 19:31 UTC, blakewilson requested changes

2024-01-22 19:31 UTC, blakewilson commented on examples/next/custom-toolbar/sonar-project.properties
This file should be removed.

2024-01-23 15:06 UTC, mindctrl commented on examples/next/custom-toolbar/DEVELOPMENT.md
> +## Updating the ACM Blueprint Export
I don't think we need this ACM info

2024-01-23 15:06 UTC, mindctrl commented on examples/next/custom-toolbar/README.md
> +# Faust Scaffold
This readme needs to be updated for this example.

2024-01-23 15:10 UTC, mindctrl requested changes
Left some comments about readme.md, development.md, and package-lock.json

2024-01-23 15:15 UTC, blakewilson reviewed
We'll also want to add `examples/next/custom-toolbar` to `package.json`'s `workspaces: { packages: [] }` so that `node_modules` are properly resolved and deduped in the monorepo.

2024-01-23 16:40 UTC, matthewguywright commented on package-lock.json
> +    },
I don't know what is going on with this PR. I used the faust-scaffold js project. Copied it in. Built from there.

2024-01-23 16:53 UTC, matthewguywright commented on package-lock.json
> +    },
I deleted the package-lock.json per @blakewilson

2024-01-23 16:56 UTC, matthewguywright commented on examples/next/custom-toolbar/package-lock.json
This won't build or pass any tests without package-lock.json

2024-01-23 17:28 UTC, blakewilson commented on package-lock.json
Deleting and recreating the `package-lock.json` may have altered versions we didn't intend to change. I think it may be safer if we just reverted this back to the version in canary:

```
git checkout canary package-lock.json
```

2024-01-24 18:53 UTC, blakewilson approved these changes

2024-01-24 20:15 UTC, merged