Toolbar should respect show avatars setting in wp
wpengine/faustjs pull request #1845
Opened 2024-03-13 20:02 UTC by TeresaGobble

## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

## Related Issue(s):

#1817 

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2024-03-13 20:18 UTC, TeresaGobble commented
The show avatar ticket is providing me with an unexpected runtime error after making changes that should permit the avatar to resolve when its value is null. I have a video, below, detailing what happens when I toggle between the wp-admin setting for showing the avatar.

The full error message is:

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'url')
```

Source
`../../../packages/faustwp-core/dist/mjs/components/Toolbar/nodes/MyAccount.js (49:0) @ AuthenticatedAccount`

```
  47 |     "Howdy, ",
  48 |     React.createElement("span", { className: "display-name" }, (_a = data === null || data === void 0 ? void 0 : data.viewer) === null || _a === void 0 ? void 0 : _a.name),
> 49 |     ((_b = data === null || data === void 0 ? void 0 : data.viewer) === null || _b === void 0 ? void 0 : _b.avatar64.url) ? (React.createElement("img", { alt: "", src: (_c = data === null || data === void 0 ? void 0 : data.viewer) === null || _c === void 0 ? void 0 : _c.avatar26.url, srcSet: `${(_d = data === null || data === void 0 ? void 0 : data.viewer) === null || _d === void 0 ? void 0 : _d.avatar52.url} 2x`, className: "avatar avatar-26 photo", height: "26", width: "26", loading: "lazy", decoding: "async" })) : null),
  50 | React.createElement(ToolbarSubmenuWrapper, null,
  51 |     React.createElement(ToolbarSubmenu, { id: "wp-admin-bar-user-actions" },
  52 |         React.createElement("li", { id: "wp-admin-bar-user-info" },

```
https://github.com/wpengine/faustjs/assets/50935135/c3f5de39-66d8-429f-b12f-54aa7605f48d

I can confirm that:

- I am on the `develop` branch of WPGraphQL
- Have added optional chaining for both images in MyAccount.tsx where the error is read from
- Have added optional chaining within the ViewerType 

I can also confirm that the Viewer is returning `avatar: null`:
![image](https://github.com/wpengine/faustjs/assets/50935135/203c4fca-78e5-4f5b-b9a8-26bb8010f123)

Any advice on next steps to try?

2024-03-14 14:00 UTC, mindctrl commented on .changeset/smooth-dogs-cough.md
> +Toolbar should respect show avatars setting in wp
Suggestion for changeset. We probably also need to indicate that WPGraphQL version 1.xx is required (don't know version yet, but I asked Jason).

```suggestion
Faust Toolbar will now respect the Show Avatars setting in WordPress.
```

2024-03-14 14:06 UTC, mindctrl requested changes
This is working as expected! I made a suggestion for the changeset and I'm waiting to hear back on the WPGraphQL version thing, which I think we need to avoid confusion and support requests about it "not working" due to being on an older version.

2024-03-14 14:26 UTC, TeresaGobble commented
> This is working as expected! I made a suggestion for the changeset and I'm waiting to hear back on the WPGraphQL version thing, which I think we need to avoid confusion and support requests about it "not working" due to being on an older version.

Thank you John! 😊 I'll hold on merging this until you hear back, and then add that detail to the changeset. I appreciate it!

2024-03-14 14:50 UTC, mindctrl commented on .changeset/smooth-dogs-cough.md
> +Faust Toolbar will now respect the Show Avatars setting in WordPress.
```suggestion
Faust Toolbar will now respect the Show Avatars setting in WordPress. Requires WPGraphQL version 1.22.1 or higher.
```

2024-03-14 15:00 UTC, merged