Fix for #1986.  Fixes various issues for content replacement for site url (draft)
wpengine/faustjs pull request #2014
Opened 2024-12-24 14:31 UTC by colinmurphy

… and also updates tests to use WP 6.6 and 6.7

Fixes various issues with using content replacement for the site URL.

## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

## Related Issue(s):

## Testing

## Screenshots

## Documentation Changes

## Dependant PRs

2024-12-24 14:36 UTC, colinmurphy commented
@josephfusco  This is the draft PR for the site URL issues.  This fixes the various issues as per our call last week but I also want to update the image srcset replacement with the same functionality so that we replace all HTTP protocols e.g. HTTP, HTTPS or //

2024-12-24 16:46 UTC, colinmurphy commented
Just noting I am working on also updating the image_source_srcset_replacement function callback aswell to use all HTTP protocols so I will have an updated PR next week after the holidays.

2024-12-30 15:47 UTC, theodesp commented
Awesome!

2024-12-30 15:59 UTC, colinmurphy commented
> Awesome!

Thanks @theodesp I have also now updated the PR with details on how to replicate the issue and test the issue.

2025-01-07 17:02 UTC, josephfusco approved these changes
Looks good to me!

![CleanShot 2025-01-07 at 12 02 09@2x](https://github.com/user-attachments/assets/c5bcb2a8-b6f4-4110-9505-a280e7ac61bd)

2025-01-08 19:19 UTC, colinmurphy commented
@josephfusco @whoami-pwd 

Can you give this another review please. Thanks @whoami-pwd for the suggestions around optimizing some the loops on our call earlier.

I have tested locally again the different config for URLs and it is all working as expected but if you could test aswell that would be great please👍

2025-01-09 15:49 UTC, whoami-pwd requested changes
Great work on addressing these issues! Please check the comments for a few suggestions.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_replace_media_url( string $content, array $wp_media_urls, string $replace_url ) {
I am not sure if this function is needed. It looks like a wrapper to the `str_replace` with an alternative parameters order.
Please remember that the `str_replace` can also accept the array as a search param, so no need to loop through each one.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_replace_urls( array $patterns, mixed $wp_site_urls, mixed $content ) {
Maybe it is better for us to keep things more simple here. Let's try to avoid using that function.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_get_wp_site_urls() {
Could you please add the return type here and to the phpdoc?

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +	$is_https = substr( $site_url, 0, 6 ) === 'https:';
`strpos` can be faster for same purpose.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +		return apply_filters( 'faustwp_get_wp_site_urls', array( $site_url ) );
Maybe we can reduce the function length and get rid off one return?

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_get_wp_media_urls() {
Let's provide some params to the function in order to eliminte some duplications of code.
Also please provide proper array typing in the doc.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
> +	$frontend_uri        = faustwp_get_setting( 'frontend_uri' );
```suggestion
	$frontend_uri  = (string) faustwp_get_setting( 'frontend_uri' ) ?: '/';
```

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
> +		$pattern_exclude_media_urls = '#' . preg_quote( $site_url, '#' ) . "(?!{$relative_upload_url}(\/|$))#";
I believe that we can implode the urls into the pattern itself instead of preg_replace it multiple times inside foreach. I guess if the urls array is less then ~50 it is faster and more compact.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
> +	if ( $replace_content_urls && $replace_media_urls ) {
Actually, if run the portion of the code for the `! $replace_media_urls ` first we can save more space here.

```suggestion
    if ( ! $replace_media_urls ) {
		$site_urls_pattern = implode( '|', array_map( 'preg_quote', $wp_site_urls ) );
		$pattern           = '#(' . $site_urls_pattern . ')(?!' . $relative_upload_url . '(\/|$))#';

		return preg_replace( $pattern, $frontend_uri, $content );
	}

	$replace = $frontend_uri . ( ! $replace_content_urls ? $relative_upload_url : '' );

	return str_replace( $wp_media_urls, $replace, $content );
```

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
>  function image_source_srcset_replacement( $sources ) {
I think we need to improve the function a little bit. It is definitely worth to keep initial comments here. And I guess there is a chance for us to make it more readable along with more compact.

2025-01-09 15:49 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +		if ( false !== strpos( $upload_dir, $site_url ) ) {
Are we checking if it starts with or contains?

2025-01-09 16:13 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_replace_urls( array $patterns, mixed $wp_site_urls, mixed $content ) {
Thanks @whoami-pwd 

I was hoping to re-use that function when I built it, but it is only used once so I will remove it 👍

2025-01-09 16:28 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +		if ( false !== strpos( $upload_dir, $site_url ) ) {
We cannot use [str_starts_with](https://www.php.net/manual/en/function.str-starts-with.php) as we need to support PHP 7.  I will look at updating this to check if it starts with the site URL

2025-01-09 18:48 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +	$is_https = substr( $site_url, 0, 6 ) === 'https:';
Thanks good to know 😄

2025-01-09 18:51 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_get_wp_site_urls() {
Good spot 💯

2025-01-09 18:52 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +		return apply_filters( 'faustwp_get_wp_site_urls', array( $site_url ) );
This probably isn't needed as the site url should be a string anyway.

2025-01-09 18:55 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
>  function image_source_srcset_replacement( $sources ) {
Ah that was updated when I ran the [phpcbf fix ](https://github.com/wpengine/faustjs/blob/canary/plugins/faustwp/composer.json#L45)

I will look at seeing what we can improve in terms of readability..

2025-01-09 19:10 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +		$pattern_exclude_media_urls = '#' . preg_quote( $site_url, '#' ) . "(?!{$relative_upload_url}(\/|$))#";
I tried to use implode but the only way I was able to do this is with array map. I don't know if the performance is worth it compared to readibility as I find the array map part not very readable.

```php
	$pattern_exclude_media_urls = '#(' . implode( '|', array_map( function( $url ) {
			return preg_quote( $url, '#' );
		}, $wp_site_urls ) ) . ")(?!{$relative_upload_url}(\/|$))#";

	return preg_replace( $pattern_exclude_media_urls, $frontend_uri, $content );
```

Happy for a better suggesting on how to do the implode part 👍

2025-01-09 19:14 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	if ( $replace_content_urls && $replace_media_urls ) {
I tested this locally and it fails a few tests. The issue is we have 3 conditions here (content and media = true, content = true or media = true).

I will see if I can take this approach and get it to work 😄

2025-01-09 19:19 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +		$pattern_exclude_media_urls = '#' . preg_quote( $site_url, '#' ) . "(?!{$relative_upload_url}(\/|$))#";
I was actually able to tidy up the array_map based on your suggestion above so thanks 😄

2025-01-09 19:21 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	if ( $replace_content_urls && $replace_media_urls ) {
Updated the PR. It should be more readable now but that part was added at the bottom of that method.

2025-01-09 19:21 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
>  function image_source_srcset_replacement( $sources ) {
Updated PHPDocs 👍

2025-01-09 19:22 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_get_wp_site_urls() {
Updated 👍

2025-01-09 19:23 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_replace_media_url( string $content, array $wp_media_urls, string $replace_url ) {
We use this function in 2 places.Happy to extract the functionality out if you prefer?

2025-01-09 19:24 UTC, colinmurphy commented
Thanks @whoami-pwd for the great code review 👍 

Can you review the changes in the latest commit please.

2025-01-10 11:34 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +		if ( false !== strpos( $upload_dir, $site_url ) ) {
Sorry, I mean that `strpos($haystack, $needle) === 0` verifies if it **starts** with and `strpos($haystack, $needle) !== false` that it **contains**.

2025-01-10 11:55 UTC, whoami-pwd requested changes
Nice work! I appreciate the updates you've made. There are still a couple of areas where we could improve the code quality/performance. Feel free to reach out if you have any questions.

2025-01-10 11:55 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +	$upload_url = faustwp_get_relative_upload_url( $wp_site_urls );
I think we can just pass the `$upload_url` here as a parameter, then we won't need to call it once again inside the function.

2025-01-10 11:55 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_replace_media_url( string $content, array $wp_media_urls, string $replace_url ) {
Yeah, my point is that the function itself is just a wrapper for the `str_replace`. We don't actually do anything except calling the `str_replace` here.

2025-01-10 11:55 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/functions.php
> +	if ( ! is_string( $upload_url ) ) {
And then we will not need the extra verification like this, because we will force parameter with string type.

2025-01-10 11:55 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
> +	$frontend_uri        = faustwp_get_setting( 'frontend_uri' );
Please typecast here to make sure it is string with some default value.

2025-01-10 11:55 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
> +	foreach ( $sources as $width => $source ) {
That would be great to improve this loop. Currently it has some memory/structure issues.
I believe that would be very helpful to have inline comments here to understand what the functionality is doing.

2025-01-10 13:01 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	foreach ( $sources as $width => $source ) {
No problem at all. I will add a few comments and review to see if we can remove the loop 👍

2025-01-10 13:09 UTC, whoami-pwd commented on plugins/faustwp/includes/replacement/callbacks.php
> +	$frontend_uri        = (string) faustwp_get_setting( 'frontend_uri' );
Probably we can use one line here with ternary or coalescing.

2025-01-10 13:16 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	$frontend_uri        = faustwp_get_setting( 'frontend_uri' );
This is not allowed by our phpcs settings 😅

2025-01-10 13:20 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/functions.php
> +function faustwp_replace_media_url( string $content, array $wp_media_urls, string $replace_url ) {
Ah sorry I see your point now. I will remove it as a function should really be doing more that one operation

2025-01-10 14:06 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	foreach ( $sources as $width => $source ) {
Updated. I added a comment about why we need to replace media srcsets when it is disabled.

We need to ensure that the wp site URL is used for both any FE URL or relative URL. The latter is a legacy issue.

2025-01-10 15:14 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	$frontend_uri        = (string) faustwp_get_setting( 'frontend_uri' );
We cannot as PHPCS settings for the plugin prevent this 👍

2025-01-10 17:24 UTC, colinmurphy commented on plugins/faustwp/includes/replacement/callbacks.php
> +	$frontend_uri        = faustwp_get_setting( 'frontend_uri' );
Sorry I was wrong here.

2025-01-13 12:20 UTC, whoami-pwd approved these changes
Nice work! 👍🏻

2025-01-14 17:32 UTC, merged