[MERL-277] docs(tip): Add Local Atlas Extension Links to getting started section
wpengine/faustjs pull request #863
Opened 2022-05-05 12:45 UTC by theodesp

This commit adds a tip to the Faust.js getting started guide mentioning
how Local Atlas extension can help saving some steps in the process.

## Description

## Related Issue(s):

MERL-277

## Testing

1. Navigate to the `/docs/tutorial/basic-headless-site` section of the docs.
2. Observe the tooltip section pertaining information about  Local Atlas Extension
 
## Screenshots
<img width="1777" alt="Screenshot 2022-05-05 at 13 44 29" src="https://user-images.githubusercontent.com/328805/166925568-035715bd-4380-4dac-b0f8-26d0ab134552.png">

## Documentation Changes

## Dependant PRs

2022-05-05 14:08 UTC, josephfusco requested changes
Thanks for adding these docs! Had one minor suggestion :)

2022-05-05 14:08 UTC, josephfusco commented on internal/website/docs/tutorial/basic-headless-site.mdx
> +With this addoned enabled, you will be able to install [**Blueprints**](https://localwp.com/help-docs/local-add-ons-help/what-are-atlas-blueprints/)
```suggestion
With this add-on enabled, you will be able to install [**Blueprints**](https://localwp.com/help-docs/local-add-ons-help/what-are-atlas-blueprints/)
```

2022-05-06 09:46 UTC, theodesp commented
@josephfusco  thank you. The typo is now fixed.

2022-05-10 12:05 UTC, blakewilson approved these changes

2022-05-11 17:06 UTC, josephfusco approved these changes

2022-05-13 09:54 UTC, merged